### ISSUE TITLE
need clarification for P.51

### ISSUE THREAD

**Issue by amiltonwong** [GANs-in-Action/gans-in-action#1]
Hi, authors,

In page 51, it is mentioned as:
```
6. Use transposed convolution, transforming the 28x28x64 tensor into the output image
size, 28x28x1.
```
However, according to Fig.4.2, it should be the following:
```
6. Use transposed convolution, transforming the 14x14x64 tensor into the output image
size, 28x28x1.
```

Please clarify for this. 
THX!

**Comment by amiltonwong** [comment]
@vbok ,

Thanks for your clarification.

BTW, when will the next chapters be released? I've read through the contents from ch1 to ch4.

**Comment by vbok** [comment]
The MEAP update with Chapter 5 should go live no later than Wednesday next week, possibly sooner. Subsequent new chapters will be added on a monthly basis.
