### ISSUE TITLE
Release Ch9 CycleGAN in advance?

### ISSUE THREAD

**Issue by amiltonwong** [GANs-in-Action/gans-in-action#2]
Hi, @vbok @jakubLangr ,

I had gone through [ch9-nb](https://github.com/GANs-in-Action/gans-in-action/tree/master/chapter-9), and would like to study the contents in details, could you release the contents of Ch9 CycleGAN on manning website in advance?

THX

**Comment by jakubLangr** [comment]
Chapter 9 released.

**Comment by amiltonwong** [comment]
THX
